require: rubocop-rspec
inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.3
  DisplayCopNames: true
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'vendor/**/*'

Lint/ImplicitStringConcatenation:
  Exclude:
  #everything here was sufia-specific

#debugger calls are expected within specs in normal operation
Lint/Debugger:
  Exclude:
    - 'spec/**/*'

Metrics/LineLength:
  Max: 400

Metrics/AbcSize:
  Max: 30
  Exclude:
  #everything here was sufia-specific
    - 'app/indexers/curation_concerns/file_set_indexer.rb'

Metrics/MethodLength:
  Max: 15
  Exclude:
    - 'lib/seed_methods.rb'
<<<<<<< HEAD
    - 'app/indexers/curation_concerns/file_set_indexer.rb'
    - 'spec/support/curation_concerns/factory_helpers.rb'
=======
>>>>>>> 5c5e30e... set fields on batch upload form
    - 'app/forms/sufia/forms/batch_upload_form.rb'

Metrics/ModuleLength:
  Exclude:
    - 'lib/seed_methods.rb'

Metrics/CyclomaticComplexity:
  Exclude:
  - 'app/forms/sufia/forms/batch_upload_form.rb'

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*'

Style/BlockEndNewline:
  Exclude:
    - 'spec/**/*'

Style/FrozenStringLiteralComment:
  Exclude:
    - 'app/controllers/contact_form_controller.rb'
    - 'app/controllers/concerns/sufia/contact_form_controller_behavior.rb'

Style/GuardClause:
  Exclude:
    - 'app/models/ability.rb'

Style/SymbolProc: # https://github.com/bbatsov/rubocop/issues/3071
  Exclude:
  #everything here was sufia-specific

Style/MultilineBlockLayout:
  Exclude:
    - 'spec/**/*'

Style/IndentationConsistency:
  EnforcedStyle: rails

Style/CollectionMethods:
  PreferredMethods:
    collect: 'map'
    collect!: 'map!'
    inject: 'reduce'
    detect: 'find'
    find_all: 'select'

Style/WordArray:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Style/BracesAroundHashParameters:
  Exclude:
    - 'spec/controllers/workgroups_controller_spec.rb'
    - 'spec/views/workgroups/edit.html.erb_spec.rb'
    - 'spec/views/workgroups/index.html.erb_spec.rb'
    - 'spec/views/workgroups/new.html.erb_spec.rb'
    - 'spec/views/workgroups/show.html.erb_spec.rb'

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

Style/RedundantSelf:
  Exclude:
    - 'config/application.rb'
    - 'config/environments/test.rb'

Style/DoubleNegation:
  Exclude:
    - 'config/environments/development.rb'

Rails:
  Enabled: true

Rails/OutputSafety:
  Exclude:
    - app/values/universal_viewer.rb

RSpec/AnyInstance:
  Exclude:
    - 'spec/controllers/contact_form_controller_spec.rb'
    - 'spec/features/admin_admin_set_spec.rb'
    - 'spec/controllers/curation_concerns/etds_controller_spec.rb'
    - 'spec/features/create_work_spec.rb'
    - 'spec/features/end_to_end_spec.rb'
    - 'spec/support/shared/doi_request.rb'
    - 'spec/models/sufia/ability_spec.rb'

RSpec/DescribeClass:
  Exclude:
    - 'spec/views/**/*'
    - 'spec/features/*'
    - 'spec/controllers/curation_concerns/generic_works_controller_spec.rb'
    - 'spec/routing/curation_concerns_spec.rb'

RSpec/DescribedClass:
  Exclude:
    - 'spec/presenters/sufia/work_show_presenter_spec.rb'

RSpec/ExpectActual:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/MessageExpectation:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/LeadingSubject:
  Enabled: false

RSpec/ExampleLength:
  Exclude:
    - 'spec/features/*'
    - 'spec/support/shared/*'
    - 'spec/forms/sufia/forms/batch_edit_form_spec.rb'

RSpec/SubjectStub:
  Enabled: false

RSpec/EmptyExampleGroup:
  Exclude:
    - 'spec/features/browse_catalog_spec.rb'
