language: ruby

rvm:
  - "2.1.6"

notifications:
  email:
    recipients:
      - hortongn@ucmail.uc.edu
      - newmanld@ucmail.uc.edu
      - scherztc@ucmail.uc.edu
      - vanmiljf@ucmail.uc.edu
      - wamsleai@ucmail.uc.edu
      - burkepk@ucmail.uc.edu
    on_success: "change"
    on_failure: "always"

bundler_args: --without headless debug

before_install:
  - gem install bundler
  - sudo apt-get update
  - sudo apt-get install libclamav-dev libclamav6 clamav clamav-base clamav-daemon clamav-freshclam clamav-unofficial-sigs
  - gem install clamav
  - sudo freshclam  
  
before_script:
  - "cp config/database.yml.sample config/database.yml"  
  - "cp config/doi.yml.sample config/doi.yml"  
  - "cp config/fedora.yml.sample config/fedora.yml"  
  - "cp config/solr.yml.sample config/solr.yml"  
  - "cp config/authentication.yml.sample config/authentication.yml"
script: "bundle exec rake ci"

