#
# To integrate your app with Google Analytics, uncomment the lines below and add your API key information.
#
analytics:
  app_name: Scholar@UC
  app_version: 3.0
  privkey_path: bamboo_analytics_privkey_path
  privkey_secret: bamboo_analytics_privkey_secret
  client_email: bamboo_analytics_client_email
