development:
  shibboleth_enabled: false 
  signups_enabled:    true

test:
  shibboleth_enabled: false 
  signups_enabled:    true 

production:
  shibboleth_enabled: false
  signups_enabled:    true 
