#
# To make browse-everything aware of a provider, uncomment the info for that provider and add your API key information.
# The file_system provider can be a path to any directory on the server where your application is running.
#
---
 box:
   :client_id: bamboo_browse_everything_box_id
   :client_secret: bamboo_browse_everything_box_secret
 kaltura:
   :partner_id: bamboo_browse_everything_kaltura_id
   :administrator_secret: bamboo_browse_everything_kaltura_secret
   :service_url: 'https://www.kaltura.com'
